AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Farmer RAG System Using AWS Lambda + API Gateway

Parameters:
  PineconeApiKey:
    Type: String
    Description: Pinecone API Key
    NoEcho: true

Resources:
  FarmerRAGLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.lambda_handler
      Runtime: python3.11
      MemorySize: 1024
      Timeout: 30
      CodeUri: src/
      Environment:
        Variables:
          EMBED_MODEL: amazon.titan-embed-text-v2:0
          LLM_MODEL: anthropic.claude-3-haiku-20240307-v1:0
          PINECONE_API_KEY: !Ref PineconeApiKey
          PINECONE_INDEX: farmer-rag-index
      Policies:
        - AmazonS3ReadOnlyAccess
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: "*"
      Events:
        ApiRequest:
          Type: Api
          Properties:
            Path: /ask
            Method: GET

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ask"
